class JSONKeys:
    EMAIL = "EmailId"
    FIRSTNAME = "FName"
    LASTNAME = "LName"
    USERTYPE = "Type"
    USERID = "UserId"
    BLOGTITLE = "BlogTitle"
    BLOGDESCRIPTION = "BlogDescription"
    IMAGELINK ="ImageLink"
    THUMBNAILlINK ="ThumbnailLink"